#!/bin/bash

# Usage, print if passed incorrect parameters
usage()
{
cat << EOF
Usage: aws-ssh argument [Options]
Argument:
	ls	Refresh listing of instances and display this listing
	config	What is the config file path and show configuration
	help	show this message
	*	Connect to the host
Options:
	(None). Everything should in config.
EOF
exit 1
}

if [ -z $1 ]; then
	usage
fi

## Configuration
aws_ssh_dir=.
aws_ssh_data_dir=${aws_ssh_dir}/data
source ${aws_ssh_dir}/config

case "$1" in
	ls)
		source ${aws_ssh_dir}/refresh.sh;;
	config)
		cat ${aws_ssh_dir}/config;;
	help | \
	--help)
		usage;;
	*)
		instance_name=$1
		source ${aws_ssh_dir}/connect.sh;;
esac
